name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid
        ports:
          - 5432:5432
        # options: >-
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5

    steps:
      - name: Baixa o código
        uses: actions/checkout@v4

      - name: Instala o PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Instala o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Instala dependências
        run: pnpm install

      - name: Roda os testes End To End
        run: pnpm test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/apisolid?schema=public'
